### ISSUE TITLE
requests.exceptions.HTTPError: 405 Client Error: METHOD NOT ALLOWED

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/dodo#75]
Error raised when attempting to call functions in `pydodo/get_flight_level.py`.

After creating the following aircraft with:
```
>>> dodo.create_aircraft('BA1', 'A320', 10., 10., 10., 2000, 200)
True
>>> dodo.all_positions()
     type  altitude  ground_speed  latitude  longitude  vertical_speed
BA1  A320    196.85          1023  10.11094   10.01987               0
```
Then running a check on the flight level for example return this error:
```
>>> dodo.get_flight_level.current_flight_level('BA1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/nats/lib/python3.6/site-packages/pydodo/get_flight_level.py", line 96, in current_flight_level
    return get_flight_level(aircraft_id)['fl_current']
  File "/usr/local/anaconda3/envs/nats/lib/python3.6/site-packages/pydodo/get_flight_level.py", line 15, in get_flight_level
    resp.raise_for_status()
  File "/usr/local/anaconda3/envs/nats/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: METHOD NOT ALLOWED for url: http://localhost:5001/api/v1/alt?acid=BA1
```
The same output occurs for both `cleared_flight_level( .. )` and `requested_flight_level( .. )` also.

### Bluesky version:
`v1.2.2` - docker image
### Bluebird version:
`v1.2.1` - docker image

**Comment by tallamjr** [comment]
This appears to be fixed with `Bluebird` `v1.3.0` following the merged PR of https://github.com/alan-turing-institute/dodo/pull/49 in `dodo`.

Closing issue for now. This should be completely resolved with the merge of https://github.com/alan-turing-institute/dodo/pull/52 and https://github.com/alan-turing-institute/bluebird/pull/68 , which would allow one to be able to use `v1.3.0` of `Bluebird` with `dodo`
